[ruby]
disabled = true
symbol = "â€¢ î‘ "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[rust]
disabled = true
symbol = "â€¢ ó°°  "
format = '[${symbol}]($style)'
style = "fg:#a48989"

[shlvl]
disabled = true
symbol = "ï…ˆ"
threshold = 2

[singularity]
disabled = true
symbol = "î‚·Sî‚µ"

[swift]
disabled = true
symbol = "ï¯£ "

[status]
disabled = true
symbol = "ï„ª"

[terraform]
disabled = true
symbol = "ï¨ˆ"

[zig]
disabled = true
symbol = "ï¼»Zï¼½"

[dotnet]
disabled = true
symbol = "î¿ "
heuristic = true

[elixir]
disabled = true
symbol = "î˜­ "

[elm]
disabled = true
symbol = "î˜¬ " # original

[env_var]
disabled = true
symbol = "î• "
variable = "0"
default = "zsh"

[erlang]
disabled = true
symbol = "î± "

[gcloud]
disabled = true
symbol = "â˜ï¸ "

[aws]
disabled = true
symbol = "îŒ½ "

[cmake]
disabled = true
symbol = "ï¨¶"

[conda]
disabled = true
symbol = "ï„Œ "
# style = "bg:#43B02A fg:#111111"
ignore_base = true
truncation_length = 1

[crystal]
disabled = true
symbol = "ïˆ™ "

[dart]
disabled = true
symbol = "î˜ " # original

[jobs]
disabled = true
symbol = " ï€º "

[julia]
disabled = true
symbol = "î˜¤ "

[kubernetes]
disabled = true
symbol = "â˜¸ï¸"

[memory_usage]
disabled = true
symbol = "ï¡š "
threshold = 75

[helm]
disabled = true
symbol = "ï´± "

[nim]
disabled = true
symbol = "î‰® "

[nix_shell]
disabled = true
symbol = "ïŒ“ "
impure_msg = '[\(impure\)](bg:#27385D fg:#FF5511)'
pure_msg = '[\(pure\)](bg:#27385D fg:#AFD700)'

[ocaml]
disabled = true
symbol = "ğŸ« "

[perl]
disabled = true
symbol = "ğŸª "

[php]
disabled = true
symbol = "î˜ˆ "

[purescript]
disabled = true
symbol = "<=>"

[hg_branch] # Mercurial
disabled = true
symbol = "â€¢ î‚  "